@startuml

skinparam style strictuml

actor User
control GpxParse
control Gpx2WormnavConverter
control GpxBoundsFactory
control Gpx2WormnavBoundsConverter
control Gpx2WormnavTrackConverter
control Gpx2WormnavPointConverter

User --> GpxParse : parse(uri)
GpxParse --> User : gpx data
User --> Gpx2WormnavConverter : convert(gpx data)

Gpx2WormnavConverter --> GpxBoundsFactory : create (gpx track data)
GpxBoundsFactory --> Gpx2WormnavConverter : gpx bounds data

Gpx2WormnavConverter --> Gpx2WormnavBoundsConverter : convert(gpx bounds edge data)
Gpx2WormnavBoundsConverter --> Gpx2WormnavBoundsConverter : iterate edge points
Gpx2WormnavBoundsConverter --> Gpx2WormnavPointConverter : convert (point data in radians , center point data in radians)
Gpx2WormnavPointConverter --> Gpx2WormnavBoundsConverter : wormnav point data
Gpx2WormnavBoundsConverter --> Gpx2WormnavConverter : wormnav bounds data

Gpx2WormnavConverter --> Gpx2WormnavConverter : get center radians form bounds

Gpx2WormnavConverter --> Gpx2WormnavTrackConverter : convert (gpx track data)
Gpx2WormnavTrackConverter --> Gpx2WormnavTrackConverter : Iterate trackpoints
Gpx2WormnavTrackConverter --> Gpx2WormnavPointConverter : convert (point data in radians , center point data in radians)
Gpx2WormnavPointConverter --> Gpx2WormnavTrackConverter : wormnav point data
Gpx2WormnavTrackConverter --> Gpx2WormnavConverter : wormnav track data

Gpx2WormnavConverter --> Gpx2WormnavConverter : assembleWormnavData()
Gpx2WormnavConverter --> User : wormnav data

@enduml